---
# Source: helm for kubernetes/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: modern-uid-65e6e813                  # Ingress name
  labels:
    app: modern-uid-65e6e813
spec:
  ingressClassName: nginx   # Optional ingressClass
  rules:
    - host: "modern-uid-65e6e813.smartops.space"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: modern-uid-65e6e813               # Links to Service name dynamically
                port:
                  number: 5173  # Links to service port dynamically
